FIND_PATH( SDHCAL_ILCCONFDB_INCLUDE_DIR NAMES ILCConfDB.h PATHS "$ENV{SDHCAL_ILCCONFDB}/include" NO_DEFAULT_PATH)
if (NOT SDHCAL_ILCCONFDB_INCLUDE_DIR)
   MESSAGE("please set the SDHCAL_ILCCONFDB environment variable to the ILCConfDB installation directory")
   MESSAGE("If ILCConfDB is not install, please run the Modules/ILC_SDHCAL_ConfDB_installer.sh installation script")
ENDIF()

if ( SDHCAL_ILCCONFDB_INCLUDE_DIR )
   GET_FILENAME_COMPONENT( SDHCAL_ILCCONFDB_ROOT ${SDHCAL_ILCCONFDB_INCLUDE_DIR} PATH )
endif()

find_library( SDHCAL_ILCCONFDB_LIBRARY ilcconfdb HINTS ${SDHCAL_ILCCONFDB_ROOT}/lib )
find_library( OCCI_LIBRARY occi HINTS ${SDHCAL_ILCCONFDB_ROOT}/lib )
find_library( CLNTSH_LIBRARY clntsh HINTS ${SDHCAL_ILCCONFDB_ROOT}/lib )
message( "library is ${SDHCAL_ILCCONFDB_LIBRARY}" )

include(FindPackageHandleStandardArgs)
# handle the QUIETLY and REQUIRED arguments and set SDHCAL_ILCCONFDB_FOUND to TRUE
# if all listed variables are TRUE
find_package_handle_standard_args(SDHCAL_ILCCONFDB DEFAULT_MSG
                                  SDHCAL_ILCCONFDB_LIBRARY SDHCAL_ILCCONFDB_INCLUDE_DIR)

mark_as_advanced(SDHCAL_ILCCONFDB_INCLUDE_DIR SDHCAL_ILCCONFDB_LIBRARY)

set(SDHCAL_ILCCONFDB_LIBRARIES ${OCCI_LIBRARY} ${CLNTSH_LIBRARY} ${SDHCAL_ILCCONFDB_LIBRARY})
set(SDHCAL_ILCCONFDB_INCLUDE_DIRS ${SDHCAL_ILCCONFDB_INCLUDE_DIR})
